-- MySQL Script generated by MySQL Workbench
-- Tue Sep 24 09:37:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taller_mecanico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taller_mecanico
-- -----------------------------------------------------
drop schema if exists taller_mecanico;
CREATE SCHEMA IF NOT EXISTS `taller_mecanico` DEFAULT CHARACTER SET utf8 ;
USE `taller_mecanico` ;

-- -----------------------------------------------------
-- Table `taller_mecanico`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller_mecanico`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `apellido` VARCHAR(100) NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_mecanico`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller_mecanico`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(15) NULL,
  `id_persona` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_persona_idx` (`id_persona` ASC) ,
  UNIQUE INDEX `id_persona_UNIQUE` (`id_persona` ASC) ,
  CONSTRAINT `fk_cliente_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `taller_mecanico`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_mecanico`.`mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller_mecanico`.`mecanico` (
  `id_mecanico` INT NOT NULL auto_increment,
  `valor_honorario` INT NULL,
  `id_persona` INT NOT NULL,
  PRIMARY KEY (`id_mecanico`),
  INDEX `fk_mecanico_persona1_idx` (`id_persona` ASC) ,
  UNIQUE INDEX `id_persona_UNIQUE` (`id_persona` ASC) ,
  CONSTRAINT `fk_mecanico_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `taller_mecanico`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_mecanico`.`vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller_mecanico`.`vehiculo` (
  `patente_vehiculo` VARCHAR(6) NOT NULL,
  `marca` VARCHAR(100) NULL,
  `modelo` VARCHAR(100) NULL,
  `agno` INT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`patente_vehiculo`),
  INDEX `fk_vehiculo_cliente1_idx` (`id_cliente` ASC) ,
  CONSTRAINT `fk_vehiculo_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `taller_mecanico`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_mecanico`.`trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller_mecanico`.`trabajo` (
  `id_trabajo` INT NOT NULL AUTO_INCREMENT,
  `fecha_ingreso` DATE NULL,
  `fecha_entrega` DATE NULL,
  `estado_inicial` VARCHAR(200) NULL,
  `reparaciones` VARCHAR(200) NULL,
  `patente_vehiculo` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id_trabajo`),
  INDEX `fk_trabajo_vehiculo1_idx` (`patente_vehiculo` ASC) ,
  CONSTRAINT `fk_trabajo_vehiculo1`
    FOREIGN KEY (`patente_vehiculo`)
    REFERENCES `taller_mecanico`.`vehiculo` (`patente_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_mecanico`.`mecanico_trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller_mecanico`.`mecanico_trabajo` (
  `id_mecanico` INT NOT NULL,
  `id_trabajo` INT NOT NULL,
  PRIMARY KEY (`id_mecanico`, `id_trabajo`),
  INDEX `fk_mecanico_has_trabajo_trabajo1_idx` (`id_trabajo` ASC) ,
  INDEX `fk_mecanico_has_trabajo_mecanico1_idx` (`id_mecanico` ASC) ,
  CONSTRAINT `fk_mecanico_has_trabajo_mecanico1`
    FOREIGN KEY (`id_mecanico`)
    REFERENCES `taller_mecanico`.`mecanico` (`id_mecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mecanico_has_trabajo_trabajo1`
    FOREIGN KEY (`id_trabajo`)
    REFERENCES `taller_mecanico`.`trabajo` (`id_trabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_mecanico`.`repuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller_mecanico`.`repuesto` (
  `num_serie_repuesto` VARCHAR(50) NOT NULL,
  `marca` VARCHAR(100) NULL,
  `costo` INT NULL,
  `id_trabajo` INT NOT NULL,
  PRIMARY KEY (`num_serie_repuesto`),
  INDEX `fk_repuesto_trabajo1_idx` (`id_trabajo` ASC) ,
  CONSTRAINT `fk_repuesto_trabajo1`
    FOREIGN KEY (`id_trabajo`)
    REFERENCES `taller_mecanico`.`trabajo` (`id_trabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
